Javascript loops practice - Matthew Kweon
MattKweon/c0822-code-solutions pull request #34
Opened 2022-09-01 19:13 UTC by MattKweon

![Screen Shot 2022-09-01 at 12 12 01 PM](https://user-images.githubusercontent.com/105886708/187994233-705a475d-6763-4188-8a32-43802a2572c1.png)

2022-09-01 21:23 UTC, codingcodymiller requested changes

2022-09-01 21:23 UTC, codingcodymiller commented on javascript-loops-practice/get-indexes.js
> +    output.splice(0, 0, i);
You should just use `unshift`

2022-09-01 21:57 UTC, MattKweon commented
![Screen Shot 2022-09-01 at 2 56 08 PM](https://user-images.githubusercontent.com/105886708/188020052-e78aa7e0-19f6-4183-a364-18470f373da7.png)

2022-09-02 16:36 UTC, codingcodymiller approved these changes

2022-09-02 18:38 UTC, merged