Css ecommerce page
MattKweon/c0822-code-solutions pull request #37
Opened 2022-09-02 01:08 UTC by MattKweon

![Screen Shot 2022-09-01 at 6 05 49 PM](https://user-images.githubusercontent.com/105886708/188037692-090fa9e7-b3ca-4bf5-ae8a-688211730fcc.png)

2022-09-02 16:50 UTC, codingcodymiller requested changes

2022-09-02 16:50 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +
`column` what? You shouldn't set column widths in pixel values, you should use percentages that match their intended size.

2022-09-07 19:09 UTC, codingcodymiller requested changes

2022-09-07 19:09 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +}
This `column` class still needs an appropriate name that identifies its size. Also, the `margin` should be applied to a separate class that you can add in addition to this class. `column` classes should only include `flex-basis` or `width`, nothing else.

2022-09-08 06:34 UTC, MattKweon commented
![Screen Shot 2022-09-07 at 11 33 13 PM](https://user-images.githubusercontent.com/105886708/189051377-d38b45cd-bd76-4622-9b80-cd04b16bf2dc.png)

2022-09-08 15:57 UTC, codingcodymiller approved these changes

2022-09-08 16:02 UTC, merged