javascript-light-bulb - Matthew Kweon
MattKweon/c0822-code-solutions pull request #44
Opened 2022-09-06 23:40 UTC by MattKweon

![Kapture 2022-09-06 at 16 38 31](https://user-images.githubusercontent.com/105886708/188758507-9458bc26-aa6c-4a96-bd1e-77e5b631aba8.gif)

2022-09-07 16:15 UTC, codingcodymiller requested changes

2022-09-07 16:15 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if (count % 2 !== 0) {
To determine whether to turn the light on or off, you are making a counter, but the only thing you ever care about is if the counter's value was even or odd. This is a situation where you would be better off using a boolean to keep track of if the light is currently on.

2022-09-07 22:33 UTC, MattKweon commented
![Kapture 2022-09-07 at 15 31 14](https://user-images.githubusercontent.com/105886708/188995152-cffffd87-4ff8-4d09-8922-b0197dbfffcf.gif)

2022-09-08 15:42 UTC, codingcodymiller requested changes

2022-09-08 15:42 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  if ($container.className === 'container off') {
Now your logic is dependent on the state of the DOM to know what to do, which is less than ideal. You should follow my initial suggestion of using a variable containing a boolean value to keep track of if the light is currently on or not, and use that variable's value to decide what action to take when the lightbulb is clicked.

2022-09-08 15:59 UTC, MattKweon commented
![Kapture 2022-09-08 at 08 59 14](https://user-images.githubusercontent.com/105886708/189169822-0aa01d8c-6562-4e29-a9dd-4be55f55a434.gif)

2022-09-09 17:35 UTC, codingcodymiller approved these changes

2022-09-09 17:51 UTC, merged