Array manipulation 3 - Matthew Kweon
MattKweon/c0822-code-solutions pull request #69
Opened 2022-09-30 01:52 UTC by MattKweon

<img width="452" alt="Screen Shot 2022-09-29 at 6 50 35 PM" src="https://user-images.githubusercontent.com/105886708/193173076-04b1149b-085b-403c-a361-1e7a5caa00d6.png">

2022-10-09 19:29 UTC, thebearingedge requested changes

2022-10-09 19:29 UTC, thebearingedge commented on array-manipulation-3/src/zip.js
> +  }
You can pick the shortest length with `Math.min`. That way you only need one loop

```js
var length = Math.min(first.length, second.length);
```

2022-10-10 21:11 UTC, MattKweon commented
![Screen Shot 2022-10-10 at 2 05 42 PM](https://user-images.githubusercontent.com/105886708/194952871-4afbab98-3a0d-425d-95fd-f7c1f7766608.png)

2022-10-10 23:06 UTC, thebearingedge approved these changes

2022-10-10 23:07 UTC, merged